import React from "react";
import NextHead from "next/head";

export function Head() {
  return (
    <NextHead>
      <title>Chet Davidson</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </NextHead>
  );
}
